@extends('layouts.app')

@section('title', 'Certificates')

@section('page-title', 'Certificates')

@section('breadcrumb')
    <li class="breadcrumb-item text-gray-900">Certificates</li>
@endsection

@section('content')

    <div class="card">
        <div class="card-header border-0 pt-6">
            <div class="card-title">
                <div class="d-flex align-items-center position-relative my-1">
                    <i class="ki-duotone ki-magnifier fs-3 position-absolute ms-5">
                        <span class="path1"></span>
                        <span class="path2"></span>
                    </i>
                    <input type="text" id="search-input" class="form-control form-control-solid w-250px ps-13"
                        placeholder="Search certificates" />
                </div>
            </div>
            <div class="card-toolbar">
                <div class="d-flex justify-content-end" data-kt-certificate-table-toolbar="base">
                    <a href="{{ route('certificates.create') }}" class="btn btn-primary">
                        <i class="ki-duotone ki-plus fs-2"></i>
                        Generate Certificate
                    </a>
                </div>
                 <!--begin::Group actions-->
                <div class="d-flex justify-content-end align-items-center gap-3 d-none" toolbar-table-1="selected">
                    <div class="fw-bold me-5">
                        <span class="me-2" toolbar-table-1="count"></span>Selected
                    </div>
                    <button type="button" class="btn btn-primary" action-select-table-1="email">Email
                        Selected</button>
                    <button type="button" class="btn btn-dark" action-select-table-1="download">Download 
                        Selected</button>
                    <button type="button" class="btn btn-danger" action-select-table-1="delete">Delete
                        Selected</button>
                </div>
                <!--end::Group actions-->
            </div>
        </div>
        <div class="card-body pt-0">
            <table class="table align-middle table-row-dashed fs-6 gy-5" id="certificates-table">
                <thead>
                    <tr class="text-start text-gray-500 fw-bold fs-7 text-uppercase gs-0">
                        <th class="w-10px pe-2">
                            <div class="form-check form-check-sm form-check-custom form-check-solid me-3">
                                <input class="form-check-input" type="checkbox" data-kt-check="true"
                                    data-kt-check-target="#table-1 .form-check-input" value="1" />
                            </div>
                        </th>
                        <th>Certificate Number</th>
                        <th>Event</th>
                        <th>Recipient</th>
                        <th>Generated By</th>
                        <th>Generated At</th>
                        <th>Status</th>
                        <th class="text-end">Actions</th>
                    </tr>
                </thead>
                <tbody class="fw-semibold text-gray-600">
                </tbody>
            </table>
        </div>
    </div>

@endsection

@push('scripts')
    <script src="{{ asset('web/js/certificates/index-table.js') }}"></script>
@endpush
