@extends('layouts.app')

@section('title', 'Certificate Details')

@section('page-title', 'Certificate Details')

@section('breadcrumb')
    <li class="breadcrumb-item">
        <a href="{{ route('certificates.index') }}" class="text-muted text-hover-primary">Certificates</a>
    </li>
    <li class="breadcrumb-item text-gray-900">{{ $certificate->certificate_number }}</li>
@endsection

@section('content')

    <div class="row g-6">
        <!--begin::Certificate Info-->
        <div class="col-lg-8">
            <div class="card mb-6">
                <div class="card-header">
                    <h3 class="card-title">Certificate Information</h3>
                </div>
                <div class="card-body">
                    <div class="row mb-7">
                        <label class="col-lg-4 fw-bold text-muted">Certificate Number</label>
                        <div class="col-lg-8">
                            <span class="fw-bold fs-6 text-gray-800">{{ $certificate->certificate_number }}</span>
                        </div>
                    </div>

                    <div class="row mb-7">
                        <label class="col-lg-4 fw-bold text-muted">Event</label>
                        <div class="col-lg-8">
                            <a href="{{ route('events.show', $certificate->event) }}"
                                class="fw-bold fs-6 text-gray-800 text-hover-primary">
                                {{ $certificate->event->name }}
                            </a>
                        </div>
                    </div>

                    <div class="row mb-7">
                        <label class="col-lg-4 fw-bold text-muted">Template</label>
                        <div class="col-lg-8">
                            <span class="fw-bold fs-6 text-gray-800">{{ $certificate->event->template->name }}</span>
                        </div>
                    </div>

                    <div class="row mb-7">
                        <label class="col-lg-4 fw-bold text-muted">Generated At</label>
                        <div class="col-lg-8">
                            <span
                                class="fw-bold fs-6 text-gray-800">{{ $certificate->generated_at->format('F d, Y H:i') }}</span>
                        </div>
                    </div>

                    <div class="row mb-7">
                        <label class="col-lg-4 fw-bold text-muted">Generated By</label>
                        <div class="col-lg-8">
                            <span class="fw-bold fs-6 text-gray-800">{{ $certificate->generator->name }}</span>
                        </div>
                    </div>

                    @if ($certificate->registration)
                        <div class="row mb-7">
                            <label class="col-lg-4 fw-bold text-muted">Registration ID</label>
                            <div class="col-lg-8">
                                <span class="fw-bold fs-6 text-gray-800">{{ $certificate->registration->id }}</span>
                            </div>
                        </div>
                    @endif

                    @if ($certificate->emailed_at)
                        <div class="row mb-7">
                            <label class="col-lg-4 fw-bold text-muted">Emailed At</label>
                            <div class="col-lg-8">
                                <span
                                    class="fw-bold fs-6 text-gray-800">{{ $certificate->emailed_at->format('F d, Y H:i') }}</span>
                            </div>
                        </div>
                    @endif

                    <div class="row mb-7">
                        <label class="col-lg-4 fw-bold text-muted">Status</label>
                        <div class="col-lg-8">
                            @if ($certificate->emailed_at)
                                <span class="badge badge-success">Emailed</span>
                            @else
                                <span class="badge badge-primary">Generated</span>
                            @endif
                        </div>
                    </div>
                </div>
            </div>

            <!--begin::Certificate Data-->
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Certificate Data</h3>
                </div>
                <div class="card-body">
                    @foreach ($certificate->data as $key => $value)
                        <div class="row mb-5">
                            <label class="col-lg-4 fw-bold text-muted">{{ ucwords(str_replace('_', ' ', $key)) }}</label>
                            <div class="col-lg-8">
                                <span class="fw-semibold fs-6 text-gray-800">{{ $value }}</span>
                            </div>
                        </div>
                    @endforeach
                </div>
            </div>
        </div>

        <!--begin::Actions Sidebar-->
        <div class="col-lg-4">
            <div class="card sticky-top" style="top: 80px;">
                <div class="card-header">
                    <h3 class="card-title">Actions</h3>
                </div>
                <div class="card-body">
                    <!--begin::Download PDF-->
                    <a href="{{ route('certificates.download', $certificate) }}" class="btn btn-primary w-100 mb-3"
                        target="_blank">
                        <i class="ki-duotone ki-cloud-download fs-2">
                            <span class="path1"></span>
                            <span class="path2"></span>
                        </i>
                        Download PDF
                    </a>

                    <!--begin::Preview-->
                    <a href="{{ route('certificates.preview', $certificate) }}" class="btn btn-light-info w-100 mb-3"
                        target="_blank">
                        <i class="ki-duotone ki-eye fs-2">
                            <span class="path1"></span>
                            <span class="path2"></span>
                            <span class="path3"></span>
                        </i>
                        Preview
                    </a>

                    <!--begin::Regenerate-->
                    <button type="button" class="btn btn-light-warning w-100 mb-3" onclick="regenerateCertificate()">
                        <i class="ki-duotone ki-arrows-circle fs-2">
                            <span class="path1"></span>
                            <span class="path2"></span>
                        </i>
                        Regenerate
                    </button>

                    <div class="separator my-5"></div>

                    <!--begin::Verification URL-->
                    <div class="mb-5">
                        <label class="form-label fw-bold">Verification URL</label>
                        <div class="input-group">
                            <input type="text" class="form-control form-control-sm" id="verification-url"
                                value="{{ $certificate->getVerificationUrl() }}" readonly>
                            <button class="btn btn-sm btn-light-primary" type="button" onclick="copyToClipboard()">
                                <i class="ki-duotone ki-copy fs-3">
                                    <span class="path1"></span>
                                    <span class="path2"></span>
                                </i>
                            </button>
                        </div>
                    </div>

                    <!--begin::QR Code-->
                    @if ($certificate->qr_code && Storage::exists($certificate->qr_code))
                        <div class="text-center mb-5">
                            <label class="form-label fw-bold">QR Code</label>
                            <div class="border rounded p-3">
                                <img src="{{ $certificate->getQrCodeUrl() }}" alt="QR Code" class="mw-100"
                                    style="max-width: 150px;">
                            </div>
                        </div>
                    @endif

                    <div class="separator my-5"></div>

                    <!--begin::Delete-->
                    <button type="button" class="btn btn-danger w-100" onclick="deleteCertificate()">
                        <i class="ki-duotone ki-trash fs-2">
                            <span class="path1"></span>
                            <span class="path2"></span>
                            <span class="path3"></span>
                            <span class="path4"></span>
                            <span class="path5"></span>
                        </i>
                        Delete Certificate
                    </button>
                </div>
            </div>
        </div>
    </div>

@endsection

@push('scripts')
    <script>
        function regenerateCertificate() {
            Swal.fire({
                text: "This will regenerate the certificate PDF. Continue?",
                icon: "question",
                showCancelButton: true,
                buttonsStyling: false,
                confirmButtonText: "Yes, regenerate!",
                cancelButtonText: "No, cancel",
                customClass: {
                    confirmButton: "btn fw-bold btn-primary",
                    cancelButton: "btn fw-bold btn-active-light-primary"
                }
            }).then(function(result) {
                if (result.value) {
                    $.ajax({
                        url: "{{ route('certificates.regenerate', $certificate) }}",
                        type: 'POST',
                        data: {
                            _token: $('meta[name="csrf-token"]').attr('content')
                        },
                        success: function(response) {
                            Swal.fire({
                                text: response.message,
                                icon: "success",
                                buttonsStyling: false,
                                confirmButtonText: "Ok, got it!",
                                customClass: {
                                    confirmButton: "btn fw-bold btn-primary",
                                }
                            }).then(function() {
                                location.reload();
                            });
                        },
                        error: function(xhr) {
                            Swal.fire({
                                text: xhr.responseJSON?.message ||
                                    "Failed to regenerate certificate",
                                icon: "error",
                                buttonsStyling: false,
                                confirmButtonText: "Ok, got it!",
                                customClass: {
                                    confirmButton: "btn fw-bold btn-primary",
                                }
                            });
                        }
                    });
                }
            });
        }

        function deleteCertificate() {
            Swal.fire({
                text: "Are you sure you want to delete this certificate? This action cannot be undone.",
                icon: "warning",
                showCancelButton: true,
                buttonsStyling: false,
                confirmButtonText: "Yes, delete it!",
                cancelButtonText: "No, return",
                customClass: {
                    confirmButton: "btn fw-bold btn-danger",
                    cancelButton: "btn fw-bold btn-active-light-primary"
                }
            }).then(function(result) {
                if (result.value) {
                    $.ajax({
                        url: "{{ route('certificates.destroy', $certificate) }}",
                        type: 'DELETE',
                        data: {
                            _token: $('meta[name="csrf-token"]').attr('content')
                        },
                        success: function(response) {
                            Swal.fire({
                                text: response.message,
                                icon: "success",
                                buttonsStyling: false,
                                confirmButtonText: "Ok, got it!",
                                customClass: {
                                    confirmButton: "btn fw-bold btn-primary",
                                }
                            }).then(function() {
                                window.location.href = "{{ route('certificates.index') }}";
                            });
                        },
                        error: function(xhr) {
                            Swal.fire({
                                text: xhr.responseJSON?.message ||
                                    "Failed to delete certificate",
                                icon: "error",
                                buttonsStyling: false,
                                confirmButtonText: "Ok, got it!",
                                customClass: {
                                    confirmButton: "btn fw-bold btn-primary",
                                }
                            });
                        }
                    });
                }
            });
        }

        function copyToClipboard() {
            const input = document.getElementById('verification-url');
            input.select();
            input.setSelectionRange(0, 99999);
            document.execCommand('copy');

            Swal.fire({
                text: "Verification URL copied to clipboard!",
                icon: "success",
                buttonsStyling: false,
                confirmButtonText: "Ok, got it!",
                customClass: {
                    confirmButton: "btn fw-bold btn-primary",
                },
                timer: 2000
            });
        }
    </script>
@endpush
